version: '3'

services:
  test-database:
    image: 'postgres:latest'
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bikeramp_api_tests